---
apiVersion: 1
datasources:
  - access: proxy
    isDefault: false
    name: Jaeger
    type: jaeger
    url: "http://jaeger:16686"
  - access: proxy
    isDefault: true
    name: Prometheus
    type: prometheus
    url: "http://prometheus:9090"
  - database: postgres
    jsonData:
      sslmode: disable
      timescaledb: false
    name: Postgres
    type: postgres
    url: "postgres:5432"
    user: postgres
