---
services:
  scaffold:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  postgres:
    ports:
      - mode: ingress
        protocol: tcp
        published: 5432
        target: 5432
  grafana:
    volumes:
      - source: "${LOCAL_WORKSPACE_FOLDER:-.}/Operations/Grafana/dashboards"
        target: /etc/grafana/provisioning/dashboards
        type: bind
      - source: "${LOCAL_WORKSPACE_FOLDER:-.}/Operations/Grafana/datasources"
        target: /etc/grafana/provisioning/datasources
        type: bind
  jaeger:
    ports:
      - mode: ingress
        protocol: udp
        published: 6831
        target: 6831
      - mode: ingress
        protocol: udp
        published: 6832
        target: 6832
      - mode: ingress
        protocol: tcp
        published: 5778
        target: 5778
      - mode: ingress
        protocol: tcp
        published: 14268
        target: 14268
      - mode: ingress
        protocol: tcp
        published: 14250
        target: 14250
  prometheus:
    volumes:
      - source: "${LOCAL_WORKSPACE_FOLDER:-.}/Operations/Prometheus/prometheus.yml"
        target: /etc/prometheus/prometheus.yml
        type: bind
version: "3.7"
