---
extensions:
  zpages:
    endpoint: "0.0.0.0:55679"

receivers:
  otlp:
    protocols:
      grpc: ~
      http:
        cors:
          allowed_origins: [http://*, https://*]

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"

processors:
  batch:
  probabilistic_sampler:
    sampling_percentage: 100
  spanmetrics:
    metrics_exporter: prometheus/spanmetrics

exporters:
  logging: ~
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090"
  prometheus/spanmetrics:
    endpoint: "0.0.0.0:8889"

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: [spanmetrics, probabilistic_sampler, batch]
      exporters: [logging, jaeger]

    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [logging, prometheus/spanmetrics]
