---
extensions: ~
receivers:
  otlp:
    protocols:
      grpc: ~
processors:
  batch: ~
exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8081"
service:
  extensions: []
  pipelines:
    metrics:
      exporters: [prometheus]
      processors: [batch]
      receivers: [otlp]
    traces:
      exporters: [jaeger]
      processors: [batch]
      receivers: [otlp]
